/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hide */

#ifndef _Included_Hide
#define _Included_Hide
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hide
 * Method:    hideInBMP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Hide_hideInBMP
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     Hide
 * Method:    hideInWAV
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Hide_hideInWAV
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     Hide
 * Method:    hideInOTHER
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Hide_hideInOTHER
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
