/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Unhide */

#ifndef _Included_Unhide
#define _Included_Unhide
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Unhide
 * Method:    unhideInBMP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Unhide_unhideInBMP
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     Unhide
 * Method:    unhideInMEDIA
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Unhide_unhideInMEDIA
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     Unhide
 * Method:    unhideInOTHER
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Unhide_unhideInOTHER
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     Unhide
 * Method:    getHiddenFileNameInBMP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Unhide_getHiddenFileNameInBMP
  (JNIEnv *, jclass);

/*
 * Class:     Unhide
 * Method:    getHiddenFileNameInMEDIA
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Unhide_getHiddenFileNameInMEDIA
  (JNIEnv *, jclass);

/*
 * Class:     Unhide
 * Method:    getHiddenFileNameInOTHER
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Unhide_getHiddenFileNameInOTHER
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
